// Full WISECP Admin API endpoint registry (authoritative paths supplied by the
// panel owner). Every endpoint the app may call is declared here once: method,
// path template ({id} placeholders) and the Group/Action permission. UI layers
// build on top of these via hooks; use `apiRequest(buildPath(...), { method })`
// for the ones without a dedicated hook yet.

export interface EndpointDef {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  permission: string;
}

// Fill {placeholders} in a path template with values.
export function buildPath(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => String(params[k] ?? ""));
}

export const ENDPOINTS = {
  system: {
    ping: { method: "GET", path: "/ping", permission: "System/Ping" },
    whoami: { method: "GET", path: "/whoami", permission: "System/Whoami" },
  },
  reference: {
    currencies: { method: "GET", path: "/reference/currencies", permission: "Reference/GetCurrencies" },
    countries: { method: "GET", path: "/reference/countries", permission: "Reference/GetCountries" },
    states: { method: "GET", path: "/reference/states", permission: "Reference/GetStates" },
    cities: { method: "GET", path: "/reference/cities", permission: "Reference/GetCities" },
    languages: { method: "GET", path: "/reference/languages", permission: "Reference/GetLanguages" },
    cycles: { method: "GET", path: "/reference/cycles", permission: "Reference/GetCycles" },
    statuses: { method: "GET", path: "/reference/statuses", permission: "Reference/GetStatuses" },
  },
  clients: {
    list: { method: "GET", path: "/clients", permission: "Clients/GetClients" },
    get: { method: "GET", path: "/clients/{id}", permission: "Clients/GetClient" },
    create: { method: "POST", path: "/clients", permission: "Clients/CreateClient" },
    update: { method: "PATCH", path: "/clients/{id}", permission: "Clients/UpdateClient" },
    delete: { method: "DELETE", path: "/clients/{id}", permission: "Clients/DeleteClient" },
    sso: { method: "POST", path: "/clients/sso", permission: "Clients/CreateClientSsoToken" },
    validate: { method: "POST", path: "/clients/validate", permission: "Clients/ValidateClient" },
    setPassword: { method: "PUT", path: "/clients/{id}/password", permission: "Clients/SetClientPassword" },
    verify: { method: "POST", path: "/clients/{id}/verify", permission: "Clients/VerifyClient" },
    set2fa: { method: "PUT", path: "/clients/{id}/2fa", permission: "Clients/SetClient2fa" },
    securitySettings: { method: "PATCH", path: "/clients/{id}/security-settings", permission: "Clients/UpdateClientSecuritySettings" },
    supportSettings: { method: "PATCH", path: "/clients/{id}/support-settings", permission: "Clients/UpdateClientSupportSettings" },
    addresses: { method: "GET", path: "/clients/{id}/addresses", permission: "Clients/GetClientAddresses" },
    address: { method: "GET", path: "/clients/{id}/addresses/{addrId}", permission: "Clients/GetClientAddress" },
    createAddress: { method: "POST", path: "/clients/{id}/addresses", permission: "Clients/CreateClientAddress" },
    updateAddress: { method: "PUT", path: "/clients/{id}/addresses/{addrId}", permission: "Clients/UpdateClientAddress" },
    deleteAddress: { method: "DELETE", path: "/clients/{id}/addresses/{addrId}", permission: "Clients/DeleteClientAddress" },
    notes: { method: "GET", path: "/clients/{id}/notes", permission: "Clients/GetClientNotes" },
    createNote: { method: "POST", path: "/clients/{id}/notes", permission: "Clients/CreateClientNote" },
    updateNote: { method: "PATCH", path: "/clients/{id}/notes/{noteId}", permission: "Clients/UpdateClientNote" },
    deleteNote: { method: "DELETE", path: "/clients/{id}/notes/{noteId}", permission: "Clients/DeleteClientNote" },
    customFields: { method: "GET", path: "/clients/{id}/custom-fields", permission: "Clients/GetClientCustomFields" },
    updateCustomFields: { method: "PATCH", path: "/clients/{id}/custom-fields", permission: "Clients/UpdateClientCustomFields" },
    block: { method: "PUT", path: "/clients/{id}/block", permission: "Clients/SetClientBlock" },
    remindInvoices: { method: "POST", path: "/clients/{id}/remind-invoices", permission: "Clients/RemindClientInvoices" },
    suspendServices: { method: "POST", path: "/clients/{id}/services/suspend", permission: "Clients/SuspendClientServices" },
    unsuspendServices: { method: "POST", path: "/clients/{id}/services/unsuspend", permission: "Clients/UnsuspendClientServices" },
    cancelServices: { method: "POST", path: "/clients/{id}/services/cancel", permission: "Clients/CancelClientServices" },
    blacklist: { method: "GET", path: "/clients/{id}/blacklist", permission: "Clients/GetClientBlacklist" },
    credits: { method: "GET", path: "/clients/{id}/credits", permission: "Clients/GetClientCredits" },
    createCredit: { method: "POST", path: "/clients/{id}/credits", permission: "Clients/CreateClientCredit" },
    updateCredit: { method: "PATCH", path: "/clients/{id}/credits/{logId}", permission: "Clients/UpdateClientCredit" },
    deleteCredit: { method: "DELETE", path: "/clients/{id}/credits/{logId}", permission: "Clients/DeleteClientCredit" },
    creditAutopay: { method: "PUT", path: "/clients/{id}/credit-autopay", permission: "Clients/SetClientCreditAutopay" },
    notifyTemplate: { method: "POST", path: "/clients/{id}/notifications/template", permission: "Clients/SendClientTemplate" },
    notifyEmail: { method: "POST", path: "/clients/{id}/notifications/email", permission: "Clients/SendClientEmail" },
    notifySms: { method: "POST", path: "/clients/{id}/notifications/sms", permission: "Clients/SendClientSms" },
    subusers: { method: "GET", path: "/clients/{id}/subusers", permission: "Clients/GetClientSubusers" },
    cards: { method: "GET", path: "/clients/{id}/cards", permission: "Clients/GetClientCards" },
    whoisProfiles: { method: "GET", path: "/clients/{id}/whois-profiles", permission: "Clients/GetClientWhoisProfiles" },
    duplicates: { method: "GET", path: "/clients/{id}/duplicates", permission: "Clients/GetClientDuplicates" },
    documents: { method: "GET", path: "/clients/{id}/documents", permission: "Clients/GetClientDocuments" },
    search: { method: "GET", path: "/clients/search", permission: "Clients/SearchClients" },
    stats: { method: "GET", path: "/clients/stats", permission: "Clients/GetClientsStats" },
    summary: { method: "GET", path: "/clients/{id}/summary", permission: "Clients/GetClientSummary" },
    latestNote: { method: "GET", path: "/clients/{id}/latest-note", permission: "Clients/GetClientLatestNote" },
    bulk: { method: "POST", path: "/clients/bulk", permission: "Clients/BulkClientActions" },
    groups: { method: "GET", path: "/clients/groups", permission: "Clients/GetClientGroups" },
    gdprRequests: { method: "GET", path: "/clients/gdpr-requests", permission: "Clients/GetGdprRequests" },
    affiliate: { method: "GET", path: "/clients/{id}/affiliate", permission: "Clients/GetClientAffiliate" },
    reseller: { method: "GET", path: "/clients/{id}/reseller", permission: "Clients/GetClientReseller" },
  },
  services: {
    list: { method: "GET", path: "/services", permission: "Services/GetServices" },
    get: { method: "GET", path: "/services/{id}", permission: "Services/GetService" },
    update: { method: "PATCH", path: "/services/{id}", permission: "Services/UpdateService" },
    delete: { method: "DELETE", path: "/services/{id}", permission: "Services/DeleteService" },
    suspend: { method: "POST", path: "/services/{id}/suspend", permission: "Services/SuspendService" },
    unsuspend: { method: "POST", path: "/services/{id}/unsuspend", permission: "Services/UnsuspendService" },
    cancel: { method: "POST", path: "/services/{id}/cancel", permission: "Services/CancelService" },
    reinstall: { method: "POST", path: "/services/{id}/reinstall", permission: "Services/ReinstallService" },
    setPassword: { method: "PUT", path: "/services/{id}/password", permission: "Services/SetServicePassword" },
    setServer: { method: "PUT", path: "/services/{id}/server", permission: "Services/SetServiceServer" },
    addons: { method: "GET", path: "/services/{id}/addons", permission: "Services/GetServiceAddons" },
    requirements: { method: "GET", path: "/services/{id}/requirements", permission: "Services/GetServiceRequirements" },
    renewalInvoice: { method: "POST", path: "/services/{id}/renewal-invoice", permission: "Services/GenerateServiceRenewalInvoice" },
    sso: { method: "POST", path: "/services/{id}/sso", permission: "Services/GetServiceSso" },
    updowngrades: { method: "GET", path: "/services/updowngrades", permission: "Services/GetUpdowngrades" },
    cancellationRequests: { method: "GET", path: "/services/cancellation-requests", permission: "Services/GetCancellationRequests" },
    transferRequests: { method: "GET", path: "/services/transfer-requests", permission: "Services/GetTransferRequests" },
  },
  orders: {
    list: { method: "GET", path: "/orders", permission: "Orders/GetOrders" },
    get: { method: "GET", path: "/orders/{id}", permission: "Orders/GetOrder" },
    create: { method: "POST", path: "/orders", permission: "Orders/CreateOrder" },
    delete: { method: "DELETE", path: "/orders/{id}", permission: "Orders/DeleteOrder" },
    update: { method: "PATCH", path: "/orders/{id}", permission: "Orders/UpdateOrder" },
    updateStatus: { method: "PUT", path: "/orders/{id}/status", permission: "Orders/UpdateOrderStatus" },
    deleteService: { method: "DELETE", path: "/orders/{id}/services/{sid}", permission: "Orders/DeleteOrderService" },
    checkDomain: { method: "POST", path: "/orders/check-domain", permission: "Orders/CheckDomain" },
    productInfo: { method: "GET", path: "/orders/product-info", permission: "Orders/GetProductInfo" },
    coupons: { method: "GET", path: "/orders/coupons", permission: "Orders/GetCoupons" },
    validateCoupons: { method: "POST", path: "/orders/validate-coupons", permission: "Orders/ValidateCoupons" },
  },
  invoices: {
    list: { method: "GET", path: "/invoices", permission: "Invoices/GetInvoices" },
    get: { method: "GET", path: "/invoices/{id}", permission: "Invoices/GetInvoice" },
    create: { method: "POST", path: "/invoices", permission: "Invoices/CreateInvoice" },
    delete: { method: "DELETE", path: "/invoices/{id}", permission: "Invoices/DeleteInvoice" },
    update: { method: "PATCH", path: "/invoices/{id}", permission: "Invoices/UpdateInvoice" },
    updateStatus: { method: "PUT", path: "/invoices/{id}/status", permission: "Invoices/UpdateInvoiceStatus" },
    clientDetails: { method: "PATCH", path: "/invoices/{id}/client-details", permission: "Invoices/UpdateInvoiceClientDetails" },
    updateItems: { method: "PUT", path: "/invoices/{id}/items", permission: "Invoices/UpdateInvoiceItems" },
    splitItems: { method: "POST", path: "/invoices/{id}/items/split", permission: "Invoices/SplitInvoiceItems" },
    addPayment: { method: "POST", path: "/invoices/{id}/payments", permission: "Invoices/AddInvoicePayment" },
    deletePayment: { method: "DELETE", path: "/invoices/{id}/payments/{paymentId}", permission: "Invoices/DeleteInvoicePayment" },
    stats: { method: "GET", path: "/invoices/stats", permission: "Invoices/GetInvoiceStats" },
    notifications: { method: "POST", path: "/invoices/{id}/notifications", permission: "Invoices/SendInvoiceNotification" },
    formalize: { method: "POST", path: "/invoices/{id}/formalize", permission: "Invoices/FormalizeInvoice" },
    remind: { method: "POST", path: "/invoices/{id}/remind", permission: "Invoices/RemindInvoice" },
    cash: { method: "GET", path: "/invoices/cash", permission: "Invoices/GetCashEntries" },
    cashSummary: { method: "GET", path: "/invoices/cash/summary", permission: "Invoices/GetCashSummary" },
    periodic: { method: "GET", path: "/invoices/periodic", permission: "Invoices/GetPeriodicExpenses" },
    periodicSummary: { method: "GET", path: "/invoices/periodic/summary", permission: "Invoices/GetPeriodicSummary" },
  },
  tickets: {
    list: { method: "GET", path: "/tickets", permission: "Tickets/GetTickets" },
    departments: { method: "GET", path: "/tickets/departments", permission: "Tickets/GetTicketDepartments" },
    assignableStaff: { method: "GET", path: "/tickets/assignable-staff", permission: "Tickets/GetTicketAssignableStaff" },
    priorities: { method: "GET", path: "/tickets/priorities", permission: "Tickets/GetTicketPriorities" },
    statuses: { method: "GET", path: "/tickets/statuses", permission: "Tickets/GetTicketStatuses" },
    stats: { method: "GET", path: "/tickets/stats", permission: "Tickets/GetTicketStats" },
    get: { method: "GET", path: "/tickets/{id}", permission: "Tickets/GetTicket" },
    update: { method: "PATCH", path: "/tickets/{id}", permission: "Tickets/UpdateTicket" },
    delete: { method: "DELETE", path: "/tickets/{id}", permission: "Tickets/DeleteTicket" },
    bulk: { method: "POST", path: "/tickets/bulk", permission: "Tickets/BulkTicketActions" },
    messages: { method: "GET", path: "/tickets/{id}/messages", permission: "Tickets/GetTicketMessages" },
    addMessage: { method: "POST", path: "/tickets/{id}/messages", permission: "Tickets/AddTicketMessage" },
    notes: { method: "GET", path: "/tickets/{id}/notes", permission: "Tickets/GetTicketNotes" },
    addNote: { method: "POST", path: "/tickets/{id}/notes", permission: "Tickets/AddTicketNote" },
    create: { method: "POST", path: "/tickets", permission: "Tickets/CreateTicket" },
    history: { method: "GET", path: "/tickets/{id}/history", permission: "Tickets/GetTicketHistory" },
    announcements: { method: "GET", path: "/tickets/announcements", permission: "Tickets/GetTicketAnnouncements" },
    settings: { method: "GET", path: "/tickets/settings", permission: "Tickets/GetTicketSettings" },
    autoTasks: { method: "GET", path: "/tickets/auto-tasks", permission: "Tickets/GetTicketAutoTasks" },
    customFields: { method: "GET", path: "/tickets/custom-fields", permission: "Tickets/GetTicketCustomFields" },
  },
  financial: {
    coupons: { method: "GET", path: "/financial/coupons", permission: "Financial/GetCoupons" },
    coupon: { method: "GET", path: "/financial/coupons/{id}", permission: "Financial/GetCoupon" },
    createCoupon: { method: "POST", path: "/financial/coupons", permission: "Financial/CreateCoupon" },
    updateCoupon: { method: "PATCH", path: "/financial/coupons/{id}", permission: "Financial/UpdateCoupon" },
    deleteCoupon: { method: "DELETE", path: "/financial/coupons/{id}", permission: "Financial/DeleteCoupon" },
    currencies: { method: "GET", path: "/financial/currencies", permission: "Financial/GetCurrencies" },
    currencySettings: { method: "GET", path: "/financial/currency-settings", permission: "Financial/GetCurrencySettings" },
    taxation: { method: "GET", path: "/financial/taxation", permission: "Financial/GetTaxation" },
    taxRules: { method: "GET", path: "/financial/tax-rules", permission: "Financial/GetTaxRules" },
  },
  notifications: {
    templates: { method: "GET", path: "/notifications/templates", permission: "Notifications/GetNotificationTemplates" },
    template: { method: "GET", path: "/notifications/templates/{group}/{key}", permission: "Notifications/GetNotificationTemplate" },
    updateTemplate: { method: "PATCH", path: "/notifications/templates/{group}/{key}", permission: "Notifications/UpdateNotificationTemplate" },
    settings: { method: "GET", path: "/notifications/settings", permission: "Notifications/GetNotificationSettings" },
  },
} as const satisfies Record<string, Record<string, EndpointDef>>;
